### ISSUE TITLE
Windows - memory leak, program not responding

### ISSUE THREAD

**Issue by daverdalas** [beckenrode/mysql-workbench-export-laravel-5-migrations#21]
Hey, I tested the plugin for my model and I came across a problem. When I try export my migrations the program is not responding and RAM consumption is growing very rapidly in time. Unfortunately, the application log is empty and the application even after a long time does not turn off. Can I provide some additional information to help solve the problem?
![przechwytywanie](https://cloud.githubusercontent.com/assets/5399813/20496629/48f2b1f4-b026-11e6-9f2b-c66c6cf2f006.JPG)
Here is my model:
[database_model.zip](https://github.com/beckenrode/mysql-workbench-export-laravel-5-migrations/files/604537/database_model.zip)

**Comment by beckenrode** [comment]
@daverdalas I was able to reproduce this on a Mac, so it isn't Windows specific. The problem seems to be from the fk_users_users1 foreign key referencing a field in the same table. As a temporary workaround you can remove that foreign key from your model and the migration files seem to generate correctly. Then manually add in the key to the _create_users_table.php migration file.

**Comment by VeeeneX** [comment]
I think I know where the issue is I will try to fix it :)

**Comment by daverdalas** [comment]
@beckenrode Yes it solved the problem :) Thank you :)

**Comment by beckenrode** [comment]
@daverdalas The latest from master should fix this issue.
